# @package _global_
defaults:
  - _self_
  - /hf

hydra:
  job:
    chdir: false
  run:
    dir: ${output_dir}
  sweep:
    dir: ${output_dir}
    subdir: ${hydra.job.override_dirname}

generations_dir: ???
reference_kind: test
reference_path: ???
embedder_checkpoint: ???

output_dir: data/inference/sample_eval
out: ${output_dir}/fmd.json

batch_size: 16
max_length: 512
device: cuda
min_chars: 40
